### PR TITLE
Buildfix

### PR DESCRIPTION
**Pull request by celerizer**

### CODE REVIEW

**Comment by RobLoach** [comment]
Would be good to know why Shaders don't load. While ignoring the error is a workaround, would be interested to see if we could *Do It Right* :tm:

**Comment by celerizer** [comment]
The error given by `glGetProgramInfoLog` is:

```
Vertex info
-----------
0(3) : error C0204: version directive must be first statement and may not be repeated
(0) : error C2003: incompatible options for link

Fragment info
-------------
0(3) : error C0204: version directive must be first statement and may not be repeated
(0) : error C2003: incompatible options for link
```

**Comment by RobLoach** [comment]
Thanks! I'll merge for now, and we can discuss further in the PR :+1:

**Comment by RobLoach** [comment]
Brought it back, while having it run is good, would like to ensure shaders are okay.

**Pull request merged**
